# Generated by Django 4.1.4 on 2023-01-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_review'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
