# Generated by Django 4.1.4 on 2023-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_image',
            field=models.ImageField(blank=True, upload_to='subimages/', verbose_name='Изображение подкатегории'),
        ),
    ]
