# Generated by Django 4.1.4 on 2023-01-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_discount_price_subcategory_sub_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to='images/', verbose_name='Доп Изображение 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(upload_to='images/', verbose_name='Доп Изображение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(upload_to='images/', verbose_name='Доп Изображение 3'),
        ),
    ]
