# Generated by Django 4.1.4 on 2023-03-20 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Только буквы, цифры и @/./+/-/_', regex='^[\\w.@+-]+\\Z')], verbose_name='название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес(url)')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='store.shoptag', verbose_name='тэг'),
        ),
    ]
